version: "2"

services:
  back:
    build: ./back
    volumes:
      - ./back/app:/app
    working_dir: /app
    command: flask run -h 0.0.0.0 -p 5000
    ports:
      - "5000:5000"
  front:
    build: ./front
    volumes:
      - ./front/app:/app
    ports:
      - "8080:8080"
